import { Translations, Language } from './types.ts';

export const REWARD_EMOJIS = [
    '🦄', '🦖', '🚀', '🍕', '🎮', '🌈', '🐱', '🤖', '🍦', 
    '🦁', '🎸', '⚽', '🦋', '🍪', '🎨', '🐶', '🎁', '⭐',
    '🍎', '🚗', '🎈', '🐼', '🍩', '🌍', '🏰', '🍄', '🐢'
];

export const TRANSLATIONS: Record<Language, Translations> = {
    ca: {
        title: "Bingo Matemàtic",
        setup_title: "Configuració",
        name_label: "Com et dius?",
        diff_label: "Nivell:",
        diff_easy: "Fàcil",
        diff_medium: "Normal",
        diff_hard: "Difícil",
        ops_label: "Operacions:",
        mode_label: "Mode de Joc:",
        mode_classic: "Clàssic",
        mode_story: "Mode Història",
        start_btn: "COMENÇAR! 🚀",
        score: "Punts",
        attempts: "Vides",
        collection: "Col·lecció",
        question: "Resol:",
        bingo_shout: "BINGO!",
        congrats: "Felicitats",
        download: "Resultats 📥",
        restart: "Tornar a jugar 🔄",
        loading_story: "Preparant el problema...",
        err_select_ops: "Selecciona una operació!",
        err_enter_name: "Escriu el teu nom!",
        max_attempts_reached: "Oh no! La resposta era:",
        failed_status: "No superat"
    },
    es: {
        title: "Bingo Matemático",
        setup_title: "Configuración",
        name_label: "¿Cómo te llamas?",
        diff_label: "Nivel:",
        diff_easy: "Fácil",
        diff_medium: "Normal",
        diff_hard: "Difícil",
        ops_label: "Operaciones:",
        mode_label: "Modo de Juego:",
        mode_classic: "Clásico",
        mode_story: "Modo Historia",
        start_btn: "¡EMPEZAR! 🚀",
        score: "Puntos",
        attempts: "Vidas",
        collection: "Colección",
        question: "Resuelve:",
        bingo_shout: "¡BINGO!",
        congrats: "Felicidades",
        download: "Resultados 📥",
        restart: "Volver a jugar 🔄",
        loading_story: "Preparando el problema...",
        err_select_ops: "¡Selecciona una operación!",
        err_enter_name: "¡Escribe tu nombre!",
        max_attempts_reached: "¡Oh no! La respuesta era:",
        failed_status: "No superado"
    },
    en: {
        title: "Math Bingo",
        setup_title: "Setup",
        name_label: "Your Name?",
        diff_label: "Level:",
        diff_easy: "Easy",
        diff_medium: "Normal",
        diff_hard: "Hard",
        ops_label: "Operations:",
        mode_label: "Game Mode:",
        mode_classic: "Classic",
        mode_story: "Story Mode",
        start_btn: "START! 🚀",
        score: "Score",
        attempts: "Lives",
        collection: "Collection",
        question: "Solve:",
        bingo_shout: "BINGO!",
        congrats: "Congratulations",
        download: "Results 📥",
        restart: "Play Again 🔄",
        loading_story: "Preparing problem...",
        err_select_ops: "Select an operation!",
        err_enter_name: "Enter your name!",
        max_attempts_reached: "Oh no! The answer was:",
        failed_status: "Failed"
    },
    gl: {
        title: "Bingo Matemático",
        setup_title: "Configuración",
        name_label: "Como te chamas?",
        diff_label: "Nivel:",
        diff_easy: "Fácil",
        diff_medium: "Normal",
        diff_hard: "Difícil",
        ops_label: "Operacións:",
        mode_label: "Modo de Xogo:",
        mode_classic: "Clásico",
        mode_story: "Modo Historia",
        start_btn: "COMEZAR! 🚀",
        score: "Puntos",
        attempts: "Vidas",
        collection: "Colección",
        question: "Resolve:",
        bingo_shout: "BINGO!",
        congrats: "Parabéns",
        download: "Resultados 📥",
        restart: "Xogar de novo 🔄",
        loading_story: "Preparando problema...",
        err_select_ops: "Selecciona unha operación!",
        err_enter_name: "Escribe o teu nome!",
        max_attempts_reached: "Vaya! A resposta era:",
        failed_status: "Non superado"
    },
    eu: {
        title: "Matematika Bingoa",
        setup_title: "Konfigurazioa",
        name_label: "Izena?",
        diff_label: "Maila:",
        diff_easy: "Erraza",
        diff_medium: "Arrunta",
        diff_hard: "Zaila",
        ops_label: "Eragiketak:",
        mode_label: "Joko Modua:",
        mode_classic: "Klasikoa",
        mode_story: "Istorio Modua",
        start_btn: "HASI! 🚀",
        score: "Puntuak",
        attempts: "Bizitzak",
        collection: "Bilduma",
        question: "Ebatzi:",
        bingo_shout: "BINGO!",
        congrats: "Zorionak",
        download: "Emaitzak 📥",
        restart: "Berriro jokatu 🔄",
        loading_story: "Arazoa prestatzen...",
        err_select_ops: "Aukeratu eragiketa bat!",
        err_enter_name: "Idatzi zure izena!",
        max_attempts_reached: "Ai ene! Erantzuna hau zen:",
        failed_status: "Ez da gainditu"
    }
};